document.writeln("<div class=\"footer bg\">");
document.writeln("	<div class=\"container\">");
document.writeln("		<div class=\"hotline\">");
document.writeln("			<h1>4001-199-399</h1>");
document.writeln("			<small>");
document.writeln("				客服热线&nbsp;&nbsp;<span>(服务时间9:00~18:00)</span>");
document.writeln("			</small>");
document.writeln("		</div>");
document.writeln("		<div class=\"contact\">");
document.writeln("			<p class=\"email\">客服邮箱  kefu@51zhangbei.com</p>");
document.writeln("			<p class=\"qq\">");
document.writeln("				<label>在线客服QQ&nbsp;&nbsp;4001199399</label>&nbsp;&nbsp;&nbsp;");
document.writeln("				<label>官方交流群QQ&nbsp;&nbsp;245064192</label>");
document.writeln("			</p>");
document.writeln("		</div>");
document.writeln("		<div class=\"map\">");
document.writeln("			<div class=\"mask\"></div>");
document.writeln("			<div class=\"address\">");
document.writeln("				<p>上海市马当路388号</p>");
document.writeln("				<p>SOHO复兴广场</p>");
document.writeln("				<p>A座22层2203室</p>");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("		<div class=\"qr_code\">");
document.writeln("			<label class=\"wx\">");
document.writeln("				<img src=\"img/wx_ewm.png\"/>");
document.writeln("				<p>微信公众号</p>");
document.writeln("			</label>");
document.writeln("			<label>");
document.writeln("				<img src=\"img/qq_ewm.png\"/>");
document.writeln("				<p>官方交流群</p>");
document.writeln("			</label>");
document.writeln("		</div>");
document.writeln("		<div class=\"icon\">");
document.writeln("			<span>");
document.writeln("				<a class=\"kxw\" href=\"javascript://\"></a>");
document.writeln("				<a class=\"cxwz\" href=\"javascript://\"></a>");
document.writeln("				<a class=\"nd\" href=\"javascript://\"></a>");
document.writeln("				<a class=\"ws360\" href=\"javascript://\"></a>");
document.writeln("			</span>");
document.writeln("		</div>");
document.writeln("		<p class=\"copyright\">Copyright © 2015 上海学呗互联网金融信息服务有限公司 沪ICP备 15038104号</p>");
document.writeln("	</div>");
