document.writeln("<div class=\"bg top_bar\">");
document.writeln("	<div class=\"container\">");
document.writeln("		<p>");
document.writeln("			客服热线   <em>4001-199-399</em>");
document.writeln("		</p>");
document.writeln("		<ul>");
document.writeln("			<li>");
document.writeln("				欢迎光临学呗！");
document.writeln("			</li>");
document.writeln("			<li>");
document.writeln("				<a>帮助中心</a>");
document.writeln("			</li>");
document.writeln("			<li>");
document.writeln("				<a>安全保障</a>");
document.writeln("			</li>");
document.writeln("			<li>");
document.writeln("				<a>新手指引</a>");
document.writeln("			</li>");
document.writeln("			<li>");
document.writeln("				<a>关于我们</a>");
document.writeln("			</li>");
document.writeln("			<li>");
document.writeln("				<a>App下载</a>");
document.writeln("			</li>");
document.writeln("			<li>");
document.writeln("				<label></label>");
document.writeln("			</li>");
document.writeln("			<li class=\"user login\">");
document.writeln("				<a>请登录</a>");
document.writeln("			</li>");
document.writeln("			<li class=\"user reg\">");
document.writeln("				<a>免费注册</a>");
document.writeln("			</li>");
document.writeln("			<!--登录后show出welcome；hide（login，reg）-->");
document.writeln("			<li class=\"user welcome\" style=\"display:none;\">");
document.writeln("				<p class=\"info\">");
document.writeln("					欢迎：<a>XXXX</a>");
document.writeln("				</p>");
document.writeln("				<!--新消息数量：手机端显示，-->");
document.writeln("				<p class=\"mess\">");
document.writeln("					<span>2</span>");
document.writeln("				</p>");
document.writeln("				<p class=\"logout\">");
document.writeln("					<a href=\"javascript://\">退出</a>");
document.writeln("				</p>");
document.writeln("			</li>");
document.writeln("		</ul>");
document.writeln("	</div>");
document.writeln("</div>");
document.writeln("");
document.writeln("<div class=\"bg nav_warp\">");
document.writeln("	<div class=\"top_nav\">");
document.writeln("		<div class=\"container\">");
document.writeln("			<div class=\"left_logo\"><a href=\"index.html\"></a></div>");
document.writeln("			<a class=\"list_btn\" href=\"javascript://\"></a>");
document.writeln("			<ul class=\"top_menu\">");
document.writeln("				<li><a>首页</a></li>");
document.writeln("				<li><a>新手专区</a></li>");
document.writeln("				<li><a>现金理财</a></li>");
document.writeln("				<li><a>专享理财</a></li>");
document.writeln("				<li><a>涨业贷</a></li>");
document.writeln("				<li class=\"my_account\">");
document.writeln("					<a class=\"falsh_light\">我的学呗</a>");
document.writeln("				</li>");
document.writeln("			</ul>");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("</div>");
document.writeln("");
document.writeln("<div class=\"right_menu\">");
document.writeln("	<ul>");
document.writeln("		<li class=\"item_1\">");
document.writeln("			<label>");
document.writeln("				<span>2</span>");
document.writeln("			</label>");
document.writeln("		</li>");
document.writeln("		<li class=\"item_2\">");
document.writeln("			<label>");
document.writeln("				");
document.writeln("			</label>");
document.writeln("		</li>");
document.writeln("		<li class=\"item_3\">");
document.writeln("			<label>");
document.writeln("			</label>");
document.writeln("			<p>400-880-0088</p>");
document.writeln("		</li>");
document.writeln("		<li class=\"item_5\">");
document.writeln("			<label>");
document.writeln("			</label>");
document.writeln("		</li>");
document.writeln("	</ul>");
document.writeln("	<div class=\"arrowup\">");
document.writeln("		<i class=\"fa fa-angle-up\"></i>");
document.writeln("	</div>");
document.writeln("</div>");