package com.sxt.models;

// Generated 2015-9-21 11:18:17 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * LdMessageTemplate generated by hbm2java
 */
public class LdMessageTemplate implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Integer uid;
	private String messageContent;
	private String status;
	private Date updateTime;
	private Date createTime;
	private Integer type;
	private Integer messageType;

	public int getMessageType() {
		return messageType;
	}

	public void setMessageType(Integer messageType) {
		this.messageType = messageType;
	}

	public LdMessageTemplate() {
	}

	public LdMessageTemplate(Integer uid, String messageContent, String status,
			Date updateTime, Date createTime, Integer type) {
		this.uid = uid;
		this.messageContent = messageContent;
		this.updateTime = updateTime;
		this.createTime = createTime;
		this.type = type;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public String getMessageContent() {
		return this.messageContent;
	}

	public void setMessageContent(String messageContent) {
		this.messageContent = messageContent;
	}

	

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

}
