package com.sxt.models;

// Generated 2015-9-10 11:43:31 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * LdMemberContactInfo generated by hbm2java
 */
public class LdMemberContactInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer uid;
	private String address;
	private String tel;
	private String contact1;
	private String contact1Re;
	private String contact1Tel;
	private String memo;
	private Date createTime;
	private Date updateTime;

	public LdMemberContactInfo() {
	}

	public LdMemberContactInfo(Integer uid, String address, String tel,
			String contact1, String contact1Re, String contact1Tel,
			Date createTime, Date updateTime) {
		this.uid = uid;
		this.address = address;
		this.tel = tel;
		this.contact1 = contact1;
		this.contact1Tel = contact1Tel;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	public LdMemberContactInfo(Integer uid, String address, String tel,
			String contact1, String contact1Re, String contact1Tel, String memo,
			Date createTime, Date updateTime) {
		this.uid = uid;
		this.address = address;
		this.tel = tel;
		this.contact1 = contact1;
		this.contact1Tel = contact1Tel;
		this.memo = memo;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getContact1() {
		return this.contact1;
	}

	public void setContact1(String contact1) {
		this.contact1 = contact1;
	}

	

	public String getContact1Re() {
		return contact1Re;
	}

	public void setContact1Re(String contact1Re) {
		this.contact1Re = contact1Re;
	}

	public String getContact1Tel() {
		return this.contact1Tel;
	}

	public void setContact1Tel(String contact1Tel) {
		this.contact1Tel = contact1Tel;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
