package com.sxt.models;

// Generated 2015-9-22 11:16:41 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * LdProductContract generated by hbm2java
 */
public class LdProductContract implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7595683312520471802L;
	private Integer id;
	private String productName;
	private String productDesc;
	private String memo;
	private Date createTime;
	private Date updateTime;
	private String status;//0 无效 1有效
	private String htmlUrl;
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getProductName() {
		return productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getProductDesc() {
		return productDesc;
	}

	public void setProductDesc(String productDesc) {
		this.productDesc = productDesc;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getHtmlUrl() {
		return this.htmlUrl;
	}

	public void setHtmlUrl(String htmlUrl) {
		this.htmlUrl = htmlUrl;
	}

}
