document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("	<head>");
document.writeln("		<meta charset=\"utf-8\">");
document.writeln("		<title>top</title>");
document.writeln("		<link rel=\"shortcut icon\" href=\"favicon.ico\" />");
document.writeln("		<link rel=\"stylesheet\" href=\"css/public.css\" />");
document.writeln("		<script type=\"text/javascript\" src=\"js/jquery-1.7.2.js\" ></script>");
document.writeln("		<script type=\"text/javascript\" src=\"js/method.js\" ></script>");
document.writeln("		<style type=\"text/css\">");
document.writeln("			@media only screen and (max-width: 1270px){");
document.writeln("				#cbl_div{left: 100%;margin-left:-50px;}");
document.writeln("				.cbl_bod{left: 100%;margin-left:-172px;}");
document.writeln("				.login_q{position: fixed;right: 0;}");
document.writeln("				.login_h{position: fixed;right: 0;}");
document.writeln("			}");
document.writeln("		</style>");
document.writeln("	</head>");
document.writeln("	<body>");
document.writeln("		<!--消息提醒-->");
document.writeln("		<div class=\"qp_ts\">新消息提醒</div>");
document.writeln("		<div class=\"qp_alert\"><p>10</p></div>");
document.writeln("		<!--侧边栏-->");
document.writeln("		<div id=\"cbl_div\">");
document.writeln("			<a href=\"javascript://\" class=\"ab_d1\"></a>");
document.writeln("			<a href=\"javascript://\" class=\"ab_d2\"></a>");
document.writeln("			<a href=\"http://wpa.b.qq.com/cgi/wpa.php?ln=2&uin=4001199399\" target=\"_blank\" class=\"ab_d3\"></a>");
document.writeln("			<a href=\"javascript://\" class=\"ab_d4\"></a>");
document.writeln("			<a href=\"#zb_nav\" class=\"ab_d5\"></a>");
document.writeln("		</div>");
document.writeln("		<div class=\"cbl_bod\">");
document.writeln("			<p>4001-199-399</p>");
document.writeln("			<img src=\"img/wx_ewm.png\" />");
document.writeln("		</div>");
document.writeln("		<!--置顶导航-->");
document.writeln("		<div id=\"zb_zdtop\">");
document.writeln("			<div class=\"zb_nav\">");
document.writeln("				<!--菜单-->");
document.writeln("				<ul>");
document.writeln("					<li class=\"zb_n1\">4001-199-399</li>");
document.writeln("					<li class=\"zb_n2\"><a href=\"javascript://\">APP下载</a></li>");
document.writeln("					<li><a href=\"javascript://\">最新公告</a></li>");
document.writeln("					<li><a href=\"javascript://\">帮助中心</a></li>");
document.writeln("					<li><a href=\"a_CompanyProfile.html\">关于我们</a></li>");
document.writeln("					<!--");
document.writeln("                    	作者：offline");
document.writeln("                    	时间：2015-11-02");
document.writeln("                    	描述：站内通知没有最新通知的时候不要给li添加class");
document.writeln("                    	      如果有最新通知，则添加class=“zntz_new”");
document.writeln("                    -->");
document.writeln("					<li class=\"zntz_new\"><a href=\"stationnews.html\">站内通知</a></li>");
document.writeln("					<li><a href=\"accounts.html\">个人中心</a></li>");
document.writeln("				</ul>");
document.writeln("				<!--登陆前-->");
document.writeln("				<div class=\"login_q\">");
document.writeln("					<a href=\"login.html\" class=\"login_a\">登录</a>");
document.writeln("					<a href=\"register.html\">注册</a>");
document.writeln("				</div>");
document.writeln("				<!--登陆后-->");
document.writeln("				<div class=\"login_h\">");
document.writeln("					<a href=\"javascript://\" class=\"close_a\">退出</a>");
document.writeln("					<p>徐先生</p>");
document.writeln("					<span>我的账户</span>");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("		<!--网站导航-->");
document.writeln("		<div id=\"zb_nav\">");
document.writeln("			<div  class=\"logo_img\" onclick=\"window.location.href=\'index.html\'\"></div>");
document.writeln("			<img src=\"img/icon/list_btn.png\" class=\"list-btn\">");
document.writeln("			<ul class=\"list_nav\">");
document.writeln("				<li><a href=\"index.html\">首页</a></li>");
document.writeln("				<li><a href=\"toInvest.html\" class=\"nav_la\">我要投资</a></li>");
document.writeln("				<li><a href=\"loan.html\">我要借款</a></li>");
document.writeln("				<li><a href=\"security.html\">安全保障</a></li>");
document.writeln("				<li><a href=\"guide.html\">新手指引</a></li>");
document.writeln("				<li><a href=\"a_CompanyProfile.html\">关于我们</a></li>");
document.writeln("				<li class=\"my_account\"><a href=\"accounts.html\">我的学呗</a></li>");
document.writeln("			</ul>");
document.writeln("		</div>");
document.writeln("	</body>");
document.writeln("</html>");
document.writeln("");